// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: prefectures.proto
package com.takusemba.gouda.protos;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class GetPrefecturesResponse extends Message<GetPrefecturesResponse, GetPrefecturesResponse.Builder> {
  public static final ProtoAdapter<GetPrefecturesResponse> ADAPTER = new ProtoAdapter_GetPrefecturesResponse();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.takusemba.gouda.protos.Prefecture#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<Prefecture> prefectures;

  public GetPrefecturesResponse(List<Prefecture> prefectures) {
    this(prefectures, ByteString.EMPTY);
  }

  public GetPrefecturesResponse(List<Prefecture> prefectures, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.prefectures = Internal.immutableCopyOf("prefectures", prefectures);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.prefectures = Internal.copyOf("prefectures", prefectures);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetPrefecturesResponse)) return false;
    GetPrefecturesResponse o = (GetPrefecturesResponse) other;
    return unknownFields().equals(o.unknownFields())
        && prefectures.equals(o.prefectures);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + prefectures.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!prefectures.isEmpty()) builder.append(", prefectures=").append(prefectures);
    return builder.replace(0, 2, "GetPrefecturesResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetPrefecturesResponse, Builder> {
    public List<Prefecture> prefectures;

    public Builder() {
      prefectures = Internal.newMutableList();
    }

    public Builder prefectures(List<Prefecture> prefectures) {
      Internal.checkElementsNotNull(prefectures);
      this.prefectures = prefectures;
      return this;
    }

    @Override
    public GetPrefecturesResponse build() {
      return new GetPrefecturesResponse(prefectures, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetPrefecturesResponse extends ProtoAdapter<GetPrefecturesResponse> {
    public ProtoAdapter_GetPrefecturesResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, GetPrefecturesResponse.class);
    }

    @Override
    public int encodedSize(GetPrefecturesResponse value) {
      return Prefecture.ADAPTER.asRepeated().encodedSizeWithTag(1, value.prefectures)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetPrefecturesResponse value) throws IOException {
      Prefecture.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.prefectures);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetPrefecturesResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.prefectures.add(Prefecture.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetPrefecturesResponse redact(GetPrefecturesResponse value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.prefectures, Prefecture.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
